# Generated by Django 4.0.5 on 2022-12-12 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ostype', '0003_alter_ostype_creator_alter_ostype_updater'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalostype',
            name='sequential_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ostype',
            name='sequential_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
