# Generated by Django 3.2.16 on 2022-11-25 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['ID'], 'verbose_name': 'Category', 'verbose_name_plural': 'Categorys'},
        ),
        migrations.AlterModelOptions(
            name='responseos',
            options={'ordering': ['ID'], 'verbose_name': 'Response Os', 'verbose_name_plural': 'Responses Os'},
        ),
    ]
