# Generated by Django 4.0.5 on 2022-12-06 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0003_auto_20221125_1532'),
        ('category', '0004_alter_category_creator_alter_category_updater_and_more'),
    ]

    operations = [
    ]
