# Generated by Django 4.0.5 on 2023-01-10 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tecnico', '0007_alter_absence_status_alter_historicalabsence_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='absence',
            name='type',
            field=models.IntegerField(choices=[(0, 'Almuerzo'), (1, 'Permiso'), (2, 'Día Libre')], default=0),
        ),
        migrations.AddField(
            model_name='historicalabsence',
            name='type',
            field=models.IntegerField(choices=[(0, 'Almuerzo'), (1, 'Permiso'), (2, 'Día Libre')], default=0),
        ),
        # migrations.RemoveField(
        #     model_name='absence',
        #     name='schedule_day',
        # ),
        # migrations.RemoveField(
        #     model_name='historicalabsence',
        #     name='schedule_day',
        # ),
    ]