# Generated by Django 4.0.5 on 2023-01-20 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tecnico', '0009_disponibility_duration_disponibility_father_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='disponibility',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='historicaldisponibility',
            name='duration',
        ),
        migrations.AddField(
            model_name='disponibility',
            name='hours_unassigned',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicaldisponibility',
            name='hours_unassigned',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
