# Generated by Django 4.0.5 on 2023-01-20 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tecnico', '0011_remove_absence_schedule_day_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='absence',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='absence',
            name='start_time',
        ),
        migrations.RemoveField(
            model_name='historicalabsence',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='historicalabsence',
            name='start_time',
        ),
        migrations.AddField(
            model_name='absence',
            name='time_end',
            field=models.DateTimeField(default='1900-01-01 00:00:00'),
        ),
        migrations.AddField(
            model_name='absence',
            name='time_start',
            field=models.DateTimeField(default='1900-01-01 00:00:00'),
        ),
        migrations.AddField(
            model_name='historicalabsence',
            name='time_end',
            field=models.DateTimeField(default='1900-01-01 00:00:00'),
        ),
        migrations.AddField(
            model_name='historicalabsence',
            name='time_start',
            field=models.DateTimeField(default='1900-01-01 00:00:00'),
        ),
    ]
