# Generated by Django 4.0.5 on 2023-01-20 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tecnico', '0012_remove_absence_end_time_remove_absence_start_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rangeofhoursavailable',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='rangeofhoursavailable',
            name='disponibility',
        ),
        migrations.RemoveField(
            model_name='rangeofhoursavailable',
            name='updater',
        ),
        migrations.DeleteModel(
            name='HistoricalRangeOfHoursAvailable',
        ),
        migrations.DeleteModel(
            name='RangeOfHoursAvailable',
        ),
    ]
