# Generated by Django 4.0.5 on 2023-01-25 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tecnico', '0013_remove_rangeofhoursavailable_creator_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='absence',
            name='time_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='absence',
            name='time_start',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalabsence',
            name='time_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalabsence',
            name='time_start',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
