# Generated by Django 4.0.5 on 2023-03-30 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tecnico', '0015_alter_absence_status_alter_historicalabsence_status_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicalholiday',
            old_name='Operator',
            new_name='operator',
        ),
        migrations.RenameField(
            model_name='holiday',
            old_name='Operator',
            new_name='operator',
        ),
    ]
