# Generated by Django 4.1.5 on 2023-03-30 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tecnico', '0016_rename_operator_historicalholiday_operator_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='disponibility',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicaldisponibility',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
