# Generated by Django 4.1.5 on 2023-04-10 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tecnico', '0017_disponibility_date_historicaldisponibility_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalschedule',
            name='schedule_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='schedule_end_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
