# Generated by Django 4.1.5 on 2023-04-13 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tecnico', '0016_technician_categories'),
        ('tecnico', '0018_alter_historicalschedule_schedule_end_date_and_more'),
    ]

    operations = [
    ]
