# Generated by Django 3.2.16 on 2022-11-26 22:37

from django.db import migrations, models
import simple_history.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Direction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('iso', models.CharField(blank=True, max_length=6, null=True)),
                ('dirtype', models.IntegerField(choices=[(0, 'País'), (1, 'Region'), (2, 'Estado'), (3, 'Municipio'), (4, 'Parroquia'), (5, 'Comuna'), (6, 'Distrito'), (7, 'Calle'), (8, 'Avenida'), (9, 'Cuadra'), (10, 'Carretera'), (11, 'Diagonal'), (12, 'Transversal'), (13, 'locacion Calle'), (15, 'Torre'), (16, 'Piso'), (17, 'Locacion Completa')])),
                ('buildingtype', models.IntegerField(blank=True, choices=[(0, 'Edificio'), (1, 'Casa'), (2, 'Puente'), (3, 'Centro Comercial'), (4, 'Quinta')], null=True)),
                ('deleted', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
            ],
            options={
                'verbose_name': 'Direction',
                'verbose_name_plural': 'Directions',
            },
        ),
        migrations.CreateModel(
            name='HistoricalDirection',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=50)),
                ('iso', models.CharField(blank=True, max_length=6, null=True)),
                ('dirtype', models.IntegerField(choices=[(0, 'País'), (1, 'Region'), (2, 'Estado'), (3, 'Municipio'), (4, 'Parroquia'), (5, 'Comuna'), (6, 'Distrito'), (7, 'Calle'), (8, 'Avenida'), (9, 'Cuadra'), (10, 'Carretera'), (11, 'Diagonal'), (12, 'Transversal'), (13, 'locacion Calle'), (15, 'Torre'), (16, 'Piso'), (17, 'Locacion Completa')])),
                ('buildingtype', models.IntegerField(blank=True, choices=[(0, 'Edificio'), (1, 'Casa'), (2, 'Puente'), (3, 'Centro Comercial'), (4, 'Quinta')], null=True)),
                ('deleted', models.BooleanField(default=False)),
                ('created', models.DateTimeField(blank=True, editable=False, null=True)),
                ('updated', models.DateTimeField(blank=True, editable=False, null=True)),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical Direction',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
