# Generated by Django 4.0.5 on 2022-12-02 17:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('direction', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='direction',
            name='buildingtype',
            field=models.IntegerField(blank=True, choices=[(0, 'edificio'), (1, 'casa'), (2, 'puente'), (3, 'centro comercial')], null=True),
        ),
        migrations.AlterField(
            model_name='direction',
            name='creator',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_creator', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='direction',
            name='dirtype',
            field=models.IntegerField(choices=[(0, 'País'), (1, 'Region'), (2, 'Estado'), (3, 'Municipio'), (4, 'Parroquia'), (5, 'Comuna'), (6, 'Distrito'), (7, 'Calle'), (8, 'Avenida'), (9, 'Cuadra'), (10, 'Carretera'), (11, 'Diagonal'), (12, 'Transversal'), (13, 'locacion calle'), (14, 'Continente'), (15, 'Quinta'), (16, 'Torre'), (17, 'Piso'), (18, 'Locacion completa'), (19, 'Manzana'), (20, 'lote')]),
        ),
        migrations.AlterField(
            model_name='direction',
            name='updater',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updater', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='historicaldirection',
            name='buildingtype',
            field=models.IntegerField(blank=True, choices=[(0, 'edificio'), (1, 'casa'), (2, 'puente'), (3, 'centro comercial')], null=True),
        ),
        migrations.AlterField(
            model_name='historicaldirection',
            name='dirtype',
            field=models.IntegerField(choices=[(0, 'País'), (1, 'Region'), (2, 'Estado'), (3, 'Municipio'), (4, 'Parroquia'), (5, 'Comuna'), (6, 'Distrito'), (7, 'Calle'), (8, 'Avenida'), (9, 'Cuadra'), (10, 'Carretera'), (11, 'Diagonal'), (12, 'Transversal'), (13, 'locacion calle'), (14, 'Continente'), (15, 'Quinta'), (16, 'Torre'), (17, 'Piso'), (18, 'Locacion completa'), (19, 'Manzana'), (20, 'lote')]),
        ),
    ]
