# Generated by Django 4.0.5 on 2022-12-02 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('direction', '0003_alter_direction_buildingtype_alter_direction_creator_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='direction',
            name='coordinates',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='historicaldirection',
            name='coordinates',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
