# Generated by Django 4.0.5 on 2023-02-23 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('direction', '0004_direction_coordinates_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='direction',
            name='full_direction',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicaldirection',
            name='full_direction',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='direction',
            name='dirtype',
            field=models.IntegerField(choices=[(0, 'País'), (1, 'Region'), (2, 'Estado'), (3, 'Municipio'), (4, 'Parroquia'), (5, 'Comuna'), (6, 'Distrito'), (7, 'Calle'), (8, 'Avenida'), (9, 'Cuadra'), (10, 'Carretera'), (11, 'Diagonal'), (12, 'Transversal'), (13, 'locacion calle'), (14, 'Continente'), (15, 'Quinta'), (16, 'Torre'), (17, 'Piso'), (18, 'Locacion completa'), (19, 'Manzana'), (20, 'lote'), (21, 'poblado')]),
        ),
        migrations.AlterField(
            model_name='historicaldirection',
            name='dirtype',
            field=models.IntegerField(choices=[(0, 'País'), (1, 'Region'), (2, 'Estado'), (3, 'Municipio'), (4, 'Parroquia'), (5, 'Comuna'), (6, 'Distrito'), (7, 'Calle'), (8, 'Avenida'), (9, 'Cuadra'), (10, 'Carretera'), (11, 'Diagonal'), (12, 'Transversal'), (13, 'locacion calle'), (14, 'Continente'), (15, 'Quinta'), (16, 'Torre'), (17, 'Piso'), (18, 'Locacion completa'), (19, 'Manzana'), (20, 'lote'), (21, 'poblado')]),
        ),
    ]
