# Generated by Django 4.1.5 on 2023-03-13 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('direction', '0006_alter_direction_dirtype_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='direction',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='historicaldirection',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
