# Generated by Django 4.0.5 on 2023-04-03 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('direction', '0008_alter_direction_name_alter_historicaldirection_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='direction',
            name='full_direction',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='direction',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='historicaldirection',
            name='full_direction',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='historicaldirection',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
