# Generated by Django 3.2.16 on 2022-11-26 22:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('OS', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ostype', '0001_initial'),
        ('direction', '0001_initial'),
        ('operador', '0001_initial'),
        ('tecnico', '0001_initial'),
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ospic',
            name='creator',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='os_ospic_creator', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ospic',
            name='owner_os',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OS.os'),
        ),
        migrations.AddField(
            model_name='ospic',
            name='updater',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='os_ospic_updater', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='os',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category.category'),
        ),
        migrations.AddField(
            model_name='os',
            name='creator',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='os_os_creator', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='os',
            name='disponibility',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='tecnico.disponibility'),
        ),
        migrations.AddField(
            model_name='os',
            name='operator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operador.operator'),
        ),
        migrations.AddField(
            model_name='os',
            name='ostype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ostype.ostype'),
        ),
        migrations.AddField(
            model_name='os',
            name='technician',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tecnico.technician'),
        ),
        migrations.AddField(
            model_name='os',
            name='updater',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='os_os_updater', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalospic',
            name='creator',
            field=models.ForeignKey(blank=True, db_constraint=False, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalospic',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalospic',
            name='owner_os',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='OS.os'),
        ),
        migrations.AddField(
            model_name='historicalospic',
            name='updater',
            field=models.ForeignKey(blank=True, db_constraint=False, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalos',
            name='category',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='category.category'),
        ),
        migrations.AddField(
            model_name='historicalos',
            name='creator',
            field=models.ForeignKey(blank=True, db_constraint=False, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalos',
            name='disponibility',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='tecnico.disponibility'),
        ),
        migrations.AddField(
            model_name='historicalos',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalos',
            name='operator',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='operador.operator'),
        ),
        migrations.AddField(
            model_name='historicalos',
            name='ostype',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='ostype.ostype'),
        ),
        migrations.AddField(
            model_name='historicalos',
            name='technician',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='tecnico.technician'),
        ),
        migrations.AddField(
            model_name='historicalos',
            name='updater',
            field=models.ForeignKey(blank=True, db_constraint=False, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicaldisplacement',
            name='creator',
            field=models.ForeignKey(blank=True, db_constraint=False, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicaldisplacement',
            name='direction_final',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='direction.direction'),
        ),
        migrations.AddField(
            model_name='historicaldisplacement',
            name='direction_init',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='direction.direction'),
        ),
        migrations.AddField(
            model_name='historicaldisplacement',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicaldisplacement',
            name='os',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='OS.os'),
        ),
        migrations.AddField(
            model_name='historicaldisplacement',
            name='updater',
            field=models.ForeignKey(blank=True, db_constraint=False, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='displacement',
            name='creator',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='os_displacement_creator', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='displacement',
            name='direction_final',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dir2', to='direction.direction'),
        ),
        migrations.AddField(
            model_name='displacement',
            name='direction_init',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dir1', to='direction.direction'),
        ),
        migrations.AddField(
            model_name='displacement',
            name='os',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OS.os'),
        ),
        migrations.AddField(
            model_name='displacement',
            name='updater',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='os_displacement_updater', to=settings.AUTH_USER_MODEL),
        ),
    ]
