# Generated by Django 4.0.5 on 2022-12-06 18:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tecnico', '0005_rangeofhoursavailable_and_more'),
        ('OS', '0003_alter_displacement_creator_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalos',
            name='disponibility',
        ),
        migrations.RemoveField(
            model_name='os',
            name='disponibility',
        ),
        migrations.AddField(
            model_name='historicalos',
            name='disponibility_hours',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='tecnico.rangeofhoursavailable'),
        ),
        migrations.AddField(
            model_name='os',
            name='disponibility_hours',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tecnico.rangeofhoursavailable'),
        ),
    ]
