# Generated by Django 4.0.5 on 2022-12-15 20:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        ('tecnico', '0006_absence_sequential_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('OS', '0004_remove_historicalos_disponibility_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='displacement',
            name='km_final',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicaldisplacement',
            name='km_final',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='TripSummary',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('deleted', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('date', models.DateField(auto_now_add=True, null=True)),
                ('status_init', models.IntegerField(blank=True, choices=[(0, 'Agendada'), (1, 'En desplazamiento'), (2, 'En atendimiento'), (3, 'Pausada'), (4, 'En espera del cliente'), (5, 'Cancelada'), (6, 'No se pudo instalar'), (7, 'Por reagendar'), (8, 'Finalizada')], null=True)),
                ('status_final', models.IntegerField(blank=True, choices=[(0, 'Agendada'), (1, 'En desplazamiento'), (2, 'En atendimiento'), (3, 'Pausada'), (4, 'En espera del cliente'), (5, 'Cancelada'), (6, 'No se pudo instalar'), (7, 'Por reagendar'), (8, 'Finalizada')], null=True)),
                ('km_init', models.IntegerField(blank=True, null=True)),
                ('km_final', models.IntegerField(blank=True, null=True)),
                ('time', models.TimeField(blank=True, null=True)),
                ('creator', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_creator', to=settings.AUTH_USER_MODEL)),
                ('nro_displacement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='OS.displacement')),
                ('nro_os', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OS.os')),
                ('technician', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tecnico.technician')),
                ('updater', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updater', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Trip Summary',
                'verbose_name_plural': 'Trip Summarys',
            },
        ),
        migrations.CreateModel(
            name='HistoricalTripSummary',
            fields=[
                ('ID', models.IntegerField(blank=True, db_index=True)),
                ('deleted', models.BooleanField(default=False)),
                ('created', models.DateTimeField(blank=True, editable=False)),
                ('updated', models.DateTimeField(blank=True, editable=False)),
                ('date', models.DateField(blank=True, editable=False, null=True)),
                ('status_init', models.IntegerField(blank=True, choices=[(0, 'Agendada'), (1, 'En desplazamiento'), (2, 'En atendimiento'), (3, 'Pausada'), (4, 'En espera del cliente'), (5, 'Cancelada'), (6, 'No se pudo instalar'), (7, 'Por reagendar'), (8, 'Finalizada')], null=True)),
                ('status_final', models.IntegerField(blank=True, choices=[(0, 'Agendada'), (1, 'En desplazamiento'), (2, 'En atendimiento'), (3, 'Pausada'), (4, 'En espera del cliente'), (5, 'Cancelada'), (6, 'No se pudo instalar'), (7, 'Por reagendar'), (8, 'Finalizada')], null=True)),
                ('km_init', models.IntegerField(blank=True, null=True)),
                ('km_final', models.IntegerField(blank=True, null=True)),
                ('time', models.TimeField(blank=True, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('creator', models.ForeignKey(blank=True, db_constraint=False, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('nro_displacement', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='OS.displacement')),
                ('nro_os', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='OS.os')),
                ('technician', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='tecnico.technician')),
                ('updater', models.ForeignKey(blank=True, db_constraint=False, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Trip Summary',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
