# Generated by Django 4.0.5 on 2023-01-20 15:43

from django.db import migrations, models
import django.db.models.deletion

def null_fields(apps, schema_editor):
    # We get the model from the versioned app registry;
    # if we directly import it, it'll be the wrong version
    Os = apps.get_model("OS", "Os")
    db_alias = schema_editor.connection.alias
    os = Os.objects.using(db_alias).all()
    if os.count() >=1:
        for item in os:
            item.disponibility_hours = None 
            item.save()

class Migration(migrations.Migration):

    dependencies = [
        ('OS', '0006_rename_km_init_historicaltripsummary_km_initial_and_more'),
    ]

    operations = [

        migrations.RunPython(null_fields),    
        migrations.AlterField(
            model_name='historicalos',
            name='disponibility_hours',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='tecnico.disponibility'),
        ),
        migrations.AlterField(
            model_name='os',
            name='disponibility_hours',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tecnico.disponibility'),
        ),
    ]