# Generated by Django 4.0.5 on 2023-02-22 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OS', '0007_alter_historicalos_disponibility_hours_and_more'),
        ('OS', '0007_historicalclient_client'),
    ]

    operations = [
    ]
