# Generated by Django 4.0.5 on 2023-02-22 20:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('direction', '0004_direction_coordinates_and_more'),
        ('OS', '0009_rename_name_client_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='direction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='direction.direction'),
        ),
        migrations.AlterField(
            model_name='historicalclient',
            name='direction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='direction.direction'),
        ),        
        migrations.AddField(
            model_name='client',
            name='operator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='operador.operator'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicalclient',
            name='operator',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='operador.operator'),
        ),        
    ]
