# Generated by Django 4.0.5 on 2023-02-23 13:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('direction', '0004_direction_coordinates_and_more'),
        ('operador', '0004_alter_historicaloperator_operator_code_and_more'),
        ('OS', '0010_alter_client_direction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='operator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operador.operator'),
        ),
        migrations.AlterField(
            model_name='historicalclient',
            name='direction',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='direction.direction'),
        ),
    ]
