# Generated by Django 4.0.5 on 2023-03-10 01:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('direction', '0006_alter_direction_dirtype_and_more'),
        ('OS', '0011_alter_client_operator_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalos',
            name='direction',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='direction.direction'),
        ),
        migrations.AddField(
            model_name='os',
            name='direction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='direction.direction'),
        ),
    ]
