# Generated by Django 4.1.5 on 2023-04-11 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OS', '0012_historicalos_direction_os_direction'),
    ]

    operations = [
        migrations.AddField(
            model_name='displacement',
            name='estimated_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicaldisplacement',
            name='estimated_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
