# Generated by Django 4.0.5 on 2022-12-02 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operador', '0003_alter_operator_creator_alter_operator_updater'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaloperator',
            name='operator_code',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='operator',
            name='operator_code',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
