# Generated by Django 4.0.5 on 2022-12-14 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0003_historicaluserapp_sequential_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicaluserapp',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical User'},
        ),
        migrations.AlterModelOptions(
            name='userapp',
            options={'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
    ]
