name: Django Deploy CI

on:
  push:
    branches: [ feature/for_servers, development, main]
  pull_request:
    branches: [ feature/for_servers, development, main]

jobs:
  build:

    runs-on: ubuntu-20.04
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.8, 3.9]

    steps:
    - uses: actions/checkout@v2
    - name: Configurando Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Instalando dependencias
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements/test.txt
    # - name: validacion de analisis de codigo 
    #   run: |
    #     pep8 brujula/
    # - name: corriendo test
    #   run: |
    #     python manage.py test

  deploy:
    runs-on: ubuntu-20.04
    steps:

    - name: ssh pipelines
      uses: cross-the-world/ssh-pipeline@master
      env:
        WELCOME: "ssh pipeline"
      with:
        host: ${{ secrets.host }}
        user: ${{ secrets.usuario }}
        pass: ${{ secrets.clave }}
        port: 22
        connect_timeout: 10s
        script: |
          source /home/usuario/.bashrc
          /home/usuario/update_brujula.sh